#!/usr/bin/env node

/**
 * Reads program fixtures from seed-fixtures/programs/ and generates seed.sql.
 *
 * Each program directory contains:
 *   program.meta.json         → name, runtime, first_party
 *   program.input-schema.json → input_schema          (JSON Schema)
 *   program.output-config.json→ output_config         (ProgramOutputConfig)
 *   program.code.js           → code
 *
 * Run:  node supabase/generate-seed.mjs
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const FIXTURES_DIR = resolve(import.meta.dirname, "seed-fixtures/programs");
const OUTPUT_FILE = resolve(import.meta.dirname, "seed.sql");

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf-8"));
}

function readText(path) {
  return readFileSync(path, "utf-8").trim();
}

function sqlEscape(str) {
  return str.replaceAll("'", "''");
}

function buildProgramValues(dirName) {
  const dir = join(FIXTURES_DIR, dirName);

  const meta = readJson(join(dir, "program.meta.json"));
  const inputSchema = readJson(join(dir, "program.input-schema.json"));
  const outputConfig = readJson(join(dir, "program.output-config.json"));
  const code = readText(join(dir, "program.code.js"));

  return {
    slug: dirName,
    name: meta.name,
    runtime: meta.runtime,
    firstParty: meta.first_party,
    code,
    inputSchema: JSON.stringify(inputSchema),
    outputConfig: JSON.stringify(outputConfig),
  };
}

const programDirs = readdirSync(FIXTURES_DIR, {
  withFileTypes: true,
})
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const programs = programDirs.map(buildProgramValues);

const programValuesSQL = programs
  .map(
    (p) =>
      `    ('${sqlEscape(p.name)}',
     '${p.runtime}',
     '${sqlEscape(p.code)}',
     '${sqlEscape(p.inputSchema)}',
     '${sqlEscape(p.outputConfig)}',
     ${p.firstParty})`,
  )
  .join(",\n");

const programCTEs = programs
  .map(
    (p) =>
      `program_${p.slug.replaceAll("-", "_")} AS (
  SELECT id FROM inserted_programs WHERE name = '${sqlEscape(p.name)}' LIMIT 1
)`,
  )
  .join(",\n\n");

const seed = `-- Auto-generated by generate-seed.mjs — do not edit by hand.
-- Source of truth: seed-fixtures/programs/

WITH

-- Programs (from fixtures)

inserted_programs AS (
  INSERT INTO program (name, runtime, code, input_schema, output_config, first_party)
  VALUES
${programValuesSQL}
  RETURNING id, name, code
),

${programCTEs},

-- Demo table

inserted_table AS (
  INSERT INTO "table" DEFAULT VALUES
  RETURNING id
),

-- Demo row

inserted_row AS (
  INSERT INTO "row" (table_id, "index")
  SELECT id, 0 FROM inserted_table
  RETURNING id
),

-- Demo columns: col 0 = user input, col 1 = uppercase transform

inserted_col1 AS (
  INSERT INTO "column" (table_id, name, "index", program_id, input_template, output_schema)
  SELECT
    t.id,
    'Input',
    0,
    p.id,
    '{"format": "string"}',
    '{"type":"string","description":"Standard text value"}'
  FROM inserted_table t, program_user_input p
  RETURNING id
),

inserted_col2 AS (
  INSERT INTO "column" (table_id, name, "index", program_id, input_template, output_schema)
  SELECT
    t.id,
    'Uppercased',
    1,
    p.id,
    '{"text_to_format.$": "$.columns.' || c1.id || '.value"}',
    '{"type":"string","description":"The capitalized string"}'
  FROM inserted_table t, program_uppercase_string p, inserted_col1 c1
  RETURNING id
),

-- Dependency: col 1 (uppercase) depends on col 0 (user input)

_dep AS (
  INSERT INTO column_dependency (source_column_id, target_column_id)
  SELECT c1.id, c2.id
  FROM inserted_col1 c1, inserted_col2 c2
),

-- Demo cells

_cell1 AS (
  INSERT INTO cell (column_id, row_id, manual_input)
  SELECT c1.id, r.id, 'hello world'
  FROM inserted_col1 c1, inserted_row r
),

_cell2 AS (
  INSERT INTO cell (column_id, row_id)
  SELECT c2.id, r.id
  FROM inserted_col2 c2, inserted_row r
)

SELECT 1;

-- Realtime: publish cell changes so the demo page can subscribe
ALTER PUBLICATION supabase_realtime ADD TABLE cell;

-- Permissive SELECT policy so the anon key can receive realtime events
CREATE POLICY "allow_select_cells" ON cell FOR SELECT USING (true);
`;

writeFileSync(OUTPUT_FILE, seed, "utf-8");
console.log(`✔ Generated ${OUTPUT_FILE}`);
console.log(
  `  ${programs.length} programs: ${programs.map((p) => p.slug).join(", ")}`,
);
