#!/usr/bin/env node

/**
 * Reads program fixtures from seed-fixtures/programs/ and generates seed.sql.
 *
 * Each program directory contains:
 *   program.meta.json         → name, first_party
 *   program.input-schema.json → input_schema          (JSON Schema)
 *   program.output-config.json→ output_config         (ProgramOutputConfig)
 *   program.code.js/ts        → code
 *
 * Run:  node supabase/generate-seed.mjs
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const FIXTURES_DIR = resolve(import.meta.dirname, "seed-fixtures/programs");
const OUTPUT_FILE = resolve(import.meta.dirname, "seed.sql");

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf-8"));
}

function readText(path) {
  return readFileSync(path, "utf-8").trim();
}

function sqlEscape(str) {
  return str.replaceAll("'", "''");
}

function buildProgramValues(dirName) {
  const dir = join(FIXTURES_DIR, dirName);

  const meta = readJson(join(dir, "program.meta.json"));
  const inputSchema = readJson(join(dir, "program.input-schema.json"));
  const outputConfig = readJson(join(dir, "program.output-config.json"));

  // Look for .ts first, fallback to .js
  let code = "";
  let filename = "main.ts";
  const filetype = "TypeScript";

  try {
    code = readText(join(dir, "program.code.ts"));
  } catch (_e) {
    code = readText(join(dir, "program.code.js"));
    filename = "main.ts"; // Keeping as .ts convention or treating JS as TS
  }

  return {
    slug: dirName,
    name: meta.name,
    firstParty: meta.first_party,
    filename,
    filetype,
    code,
    inputSchema: JSON.stringify(inputSchema),
    outputConfig: JSON.stringify(outputConfig),
  };
}

const programDirs = readdirSync(FIXTURES_DIR, {
  withFileTypes: true,
})
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const programs = programDirs.map(buildProgramValues);

const programInserts = programs
  .map((p) => {
    const slug = p.slug.replaceAll("-", "_");
    return `
-- ${p.name}
inserted_program_${slug} AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, '${sqlEscape(p.name)}', ${p.firstParty} FROM system_profile
  RETURNING id
),
inserted_version_${slug} AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '${sqlEscape(p.inputSchema)}', '${sqlEscape(p.outputConfig)}' FROM inserted_program_${slug}
  RETURNING id
),
inserted_file_${slug} AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, '${p.filename}', '${p.filetype}', '${sqlEscape(p.code)}'
  FROM system_profile p, inserted_version_${slug} v
  RETURNING id
)`;
  })
  .join(",\n");

const programVersionCTEs = programs
  .map(
    (p) =>
      `program_version_${p.slug.replaceAll("-", "_")} AS (
  SELECT id FROM inserted_version_${p.slug.replaceAll("-", "_")} LIMIT 1
)`,
  )
  .join(",\n\n");

const seed = `-- Auto-generated by generate-seed.mjs — do not edit by hand.
-- Source of truth: seed-fixtures/programs/

-- 1. Create a dummy user in auth.users
INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token) 
VALUES ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'seed@example.com', 'crypt', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{}', NOW(), NOW(), '', '', '', '')
ON CONFLICT (id) DO NOTHING;

WITH

-- Create a system profile to own the seeded data
system_profile AS (
  INSERT INTO "profile" (type, name, external_name, owner_user_id)
  VALUES ('Agent', 'System Agent', 'system', '00000000-0000-0000-0000-000000000000')
  RETURNING id
),

-- Programs (from fixtures)
${programInserts},

${programVersionCTEs},

-- Demo table

inserted_table AS (
  INSERT INTO "table" (owner_profile_id, name)
  SELECT id, 'Demo Table' FROM system_profile
  RETURNING id
),

-- Demo row

inserted_row AS (
  INSERT INTO "row" (table_id, "idx")
  SELECT id, 0 FROM inserted_table
  RETURNING id
),

-- Demo columns: col 0 = user input, col 1 = uppercase transform

inserted_col1 AS (
  INSERT INTO "column" (table_id, name, "idx", program_version_id, input_template, output_schema)
  SELECT
    t.id,
    'Input',
    0,
    p.id,
    '{"format": "string"}',
    '{"type":"string","description":"Standard text value"}'
  FROM inserted_table t, program_version_user_input p
  RETURNING id
),

inserted_col2 AS (
  INSERT INTO "column" (table_id, name, "idx", program_version_id, input_template, output_schema)
  SELECT
    t.id,
    'Uppercased',
    1,
    p.id,
    '{"text_to_format.$": "$.columns.' || c1.id || '.value"}',
    '{"type":"string","description":"The capitalized string"}'
  FROM inserted_table t, program_version_uppercase_string p, inserted_col1 c1
  RETURNING id
),

-- Dependency: col 1 (uppercase) depends on col 0 (user input)

_dep AS (
  INSERT INTO column_dependency (source_column_id, target_column_id)
  SELECT c1.id, c2.id
  FROM inserted_col1 c1, inserted_col2 c2
),

-- Demo cells

_cell1 AS (
  INSERT INTO cell (column_id, row_id, manual_input)
  SELECT c1.id, r.id, 'hello world'
  FROM inserted_col1 c1, inserted_row r
),

_cell2 AS (
  INSERT INTO cell (column_id, row_id)
  SELECT c2.id, r.id
  FROM inserted_col2 c2, inserted_row r
)

SELECT 1;

-- Realtime: publish cell changes so the demo page can subscribe
ALTER PUBLICATION supabase_realtime ADD TABLE cell;

-- Permissive SELECT policy so the anon key can receive realtime events
-- NOTE: In a real environment, RLS should handle this, but for the seed/demo, we ensure it's open.
-- We drop it first to avoid errors if the seed runs multiple times.
DROP POLICY IF EXISTS "allow_select_cells" ON cell;
CREATE POLICY "allow_select_cells" ON cell FOR SELECT USING (true);
`;

writeFileSync(OUTPUT_FILE, seed, "utf-8");
console.log(`✔ Generated ${OUTPUT_FILE}`);
console.log(
  `  ${programs.length} programs: ${programs.map((p) => p.slug).join(", ")}`,
);
