-- Auto-generated by generate-seed.mjs — do not edit by hand.
-- Source of truth: seed-fixtures/programs/

WITH

-- Programs (from fixtures)

inserted_programs AS (
  INSERT INTO program (name, runtime, code, input_schema, output_config, first_party)
  VALUES
    ('Formula',
     'JavaScript',
     'export default ({ input }) => {
  const raw = input.formula;

  if (typeof raw !== "string") {
    return raw;
  }

  // Attempt to evaluate it as a JavaScript expression.
  // If the user types a literal string like `Hello {{name}}`,
  // it will throw a SyntaxError and we''ll fallback to returning it directly.
  // If they type `1 + 1` or `["a", "b"].join(",")`, it evaluates to the result.
  try {
    const fn = new Function(`return (${raw});`);
    return fn();
  } catch {
    return raw;
  }
};',
     '{"type":"object","properties":{"formula":{"type":"string","title":"Formula"}},"required":["formula"]}',
     '{"schema":{"type":"string","description":"Computed formula result"}}',
     true),
    ('API Request',
     'JavaScript',
     'export default async ({ input }) => {
  const options = {
    method: input.method,
    headers: input.headers,
  };

  if (input.method !== "GET" && input.payload) {
    options.body = JSON.stringify(input.payload);
    options.headers = {
      "Content-Type": "application/json",
      ...options.headers,
    };
  }

  const res = await fetch(input.url, options);

  if (!res.ok) {
    let errorBody;
    try {
      errorBody = await res.json();
    } catch {
      errorBody = await res.text();
    }

    throw new Error(
      JSON.stringify({
        status: res.status,
        statusText: res.statusText,
        body: errorBody,
      }),
    );
  }

  return res.json();
};',
     '{"type":"object","properties":{"method":{"type":"string","enum":["GET","POST","PUT","DELETE"],"default":"GET"},"url":{"type":"string","format":"uri","title":"Endpoint URL"},"headers":{"type":"object","additionalProperties":{"type":"string"},"title":"Headers (JSON)"},"payload":{"type":"object","additionalProperties":true,"title":"Body / Payload"}},"required":["method","url"]}',
     '{"flags":{"allowInference":true},"schema":{"type":"object","additionalProperties":true,"description":"Generic HTTP response payload (unknown shape)"}}',
     true),
    ('Execute SQL',
     'JavaScript',
     'export default async ({ input }) => {
  throw new Error(
    `SQL execution for ${input.connection.dialect} is not yet implemented`,
  );
};',
     '{"type":"object","properties":{"connection":{"type":"object","properties":{"dialect":{"type":"string","enum":["Postgres","MySQL"]},"return_mode":{"type":"string","enum":["Rows","Count"]}}},"query":{"type":"string","title":"SQL Query"}},"required":["connection","query"]}',
     '{"flags":{"allowInference":true},"schema":{"type":"array","items":{"type":"object"},"description":"Query result rows"},"overloads":[{"match":{"connection.return_mode":"Count"},"schema":{"type":"number","description":"The total number of matching rows"}}]}',
     true),
    ('Uppercase String',
     'JavaScript',
     'export default ({ input }) => input.text_to_format.toUpperCase();',
     '{"type":"object","properties":{"text_to_format":{"type":"string","title":"Text","description":"The string you want to capitalize"}},"required":["text_to_format"]}',
     '{"flags":{},"schema":{"type":"string","description":"The capitalized string"}}',
     true),
    ('User Input',
     'JavaScript',
     'export default ({ input, cell }) => {
  const raw = cell.manualInputValue;

  switch (input.format) {
    case "number":
      return Number(raw);
    case "boolean":
      return raw?.toLowerCase() === "true";
    default:
      return raw;
  }
};',
     '{"type":"object","properties":{"format":{"type":"string","enum":["string","number","boolean"],"title":"Column Type","default":"string"}},"required":["format"]}',
     '{"flags":{"allowManualInput":true},"schema":{"type":"string","description":"Standard text value"},"overloads":[{"match":{"format":"number"},"schema":{"type":"number"}},{"match":{"format":"boolean"},"schema":{"type":"boolean"}}]}',
     true)
  RETURNING id, name, code
),

program_formula AS (
  SELECT id FROM inserted_programs WHERE name = 'Formula' LIMIT 1
),

program_http_request AS (
  SELECT id FROM inserted_programs WHERE name = 'API Request' LIMIT 1
),

program_sql_query AS (
  SELECT id FROM inserted_programs WHERE name = 'Execute SQL' LIMIT 1
),

program_uppercase_string AS (
  SELECT id FROM inserted_programs WHERE name = 'Uppercase String' LIMIT 1
),

program_user_input AS (
  SELECT id FROM inserted_programs WHERE name = 'User Input' LIMIT 1
),

-- Demo table

inserted_table AS (
  INSERT INTO "table" DEFAULT VALUES
  RETURNING id
),

-- Demo row

inserted_row AS (
  INSERT INTO "row" (table_id, "index")
  SELECT id, 0 FROM inserted_table
  RETURNING id
),

-- Demo columns: col 0 = user input, col 1 = uppercase transform

inserted_col1 AS (
  INSERT INTO "column" (table_id, name, "index", program_id, input_template, output_schema)
  SELECT
    t.id,
    'Input',
    0,
    p.id,
    '{"format": "string"}',
    '{"type":"string","description":"Standard text value"}'
  FROM inserted_table t, program_user_input p
  RETURNING id
),

inserted_col2 AS (
  INSERT INTO "column" (table_id, name, "index", program_id, input_template, output_schema)
  SELECT
    t.id,
    'Uppercased',
    1,
    p.id,
    '{"text_to_format.$": "$.columns.' || c1.id || '.value"}',
    '{"type":"string","description":"The capitalized string"}'
  FROM inserted_table t, program_uppercase_string p, inserted_col1 c1
  RETURNING id
),

-- Dependency: col 1 (uppercase) depends on col 0 (user input)

_dep AS (
  INSERT INTO column_dependency (source_column_id, target_column_id)
  SELECT c1.id, c2.id
  FROM inserted_col1 c1, inserted_col2 c2
),

-- Demo cells

_cell1 AS (
  INSERT INTO cell (column_id, row_id, manual_input)
  SELECT c1.id, r.id, 'hello world'
  FROM inserted_col1 c1, inserted_row r
),

_cell2 AS (
  INSERT INTO cell (column_id, row_id)
  SELECT c2.id, r.id
  FROM inserted_col2 c2, inserted_row r
)

SELECT 1;

-- Realtime: publish cell changes so the demo page can subscribe
ALTER PUBLICATION supabase_realtime ADD TABLE cell;

-- Permissive SELECT policy so the anon key can receive realtime events
CREATE POLICY "allow_select_cells" ON cell FOR SELECT USING (true);
