-- Auto-generated by generate-seed.mjs — do not edit by hand.
-- Source of truth: seed-fixtures/programs/

-- 1. Create a dummy user in auth.users
INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token) 
VALUES ('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'seed@example.com', 'crypt', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{}', NOW(), NOW(), '', '', '', '')
ON CONFLICT (id) DO NOTHING;

WITH

-- Create a system profile to own the seeded data
system_profile AS (
  INSERT INTO "profile" (type, name, external_name, owner_user_id)
  VALUES ('Agent', 'System Agent', 'system', '00000000-0000-0000-0000-000000000000')
  RETURNING id
),

-- Programs (from fixtures)

-- Formula
inserted_program_formula AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, 'Formula', true FROM system_profile
  RETURNING id
),
inserted_version_formula AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '{"type":"object","properties":{"formula":{"type":"string","title":"Formula"}},"required":["formula"]}', '{"schema":{"type":"string","description":"Computed formula result"}}' FROM inserted_program_formula
  RETURNING id
),
inserted_file_formula_0 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'input-schema.json', 'Json', '{
  "type": "object",
  "properties": {
    "formula": {
      "type": "string",
      "title": "Formula"
    }
  },
  "required": ["formula"]
}'
  FROM system_profile p, inserted_version_formula v
  RETURNING id
),
inserted_file_formula_1 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'main.ts', 'TypeScript', 'export default ({ input }) => {
  const raw = input.formula;

  if (typeof raw !== "string") {
    return raw;
  }

  // Attempt to evaluate it as a JavaScript expression.
  // If the user types a literal string like `Hello {{name}}`,
  // it will throw a SyntaxError and we''ll fallback to returning it directly.
  // If they type `1 + 1` or `["a", "b"].join(",")`, it evaluates to the result.
  try {
    const fn = new Function(`return (${raw});`);
    return fn();
  } catch {
    return raw;
  }
};'
  FROM system_profile p, inserted_version_formula v
  RETURNING id
),
inserted_file_formula_2 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'output-config.json', 'Json', '{
  "schema": {
    "type": "string",
    "description": "Computed formula result"
  }
}'
  FROM system_profile p, inserted_version_formula v
  RETURNING id
),
inserted_file_formula_3 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'package.json', 'Json', '{
  "name": "Formula"
}'
  FROM system_profile p, inserted_version_formula v
  RETURNING id
),

-- API Request
inserted_program_http_request AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, 'API Request', true FROM system_profile
  RETURNING id
),
inserted_version_http_request AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '{"type":"object","properties":{"method":{"type":"string","enum":["GET","POST","PUT","DELETE"],"default":"GET"},"url":{"type":"string","format":"uri","title":"Endpoint URL"},"headers":{"type":"object","additionalProperties":{"type":"string"},"title":"Headers (JSON)"},"payload":{"type":"object","additionalProperties":true,"title":"Body / Payload"}},"required":["method","url"]}', '{"flags":{"allowInference":true},"schema":{"type":"object","additionalProperties":true,"description":"Generic HTTP response payload (unknown shape)"}}' FROM inserted_program_http_request
  RETURNING id
),
inserted_file_http_request_0 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'input-schema.json', 'Json', '{
  "type": "object",
  "properties": {
    "method": {
      "type": "string",
      "enum": ["GET", "POST", "PUT", "DELETE"],
      "default": "GET"
    },
    "url": {
      "type": "string",
      "format": "uri",
      "title": "Endpoint URL"
    },
    "headers": {
      "type": "object",
      "additionalProperties": { "type": "string" },
      "title": "Headers (JSON)"
    },
    "payload": {
      "type": "object",
      "additionalProperties": true,
      "title": "Body / Payload"
    }
  },
  "required": ["method", "url"]
}'
  FROM system_profile p, inserted_version_http_request v
  RETURNING id
),
inserted_file_http_request_1 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'main.ts', 'TypeScript', 'export default async ({ input }) => {
  const options = {
    method: input.method,
    headers: input.headers,
  };

  if (input.method !== "GET" && input.payload) {
    options.body = JSON.stringify(input.payload);
    options.headers = {
      "Content-Type": "application/json",
      ...options.headers,
    };
  }

  const res = await fetch(input.url, options);

  if (!res.ok) {
    let errorBody;
    try {
      errorBody = await res.json();
    } catch {
      errorBody = await res.text();
    }

    throw new Error(
      JSON.stringify({
        status: res.status,
        statusText: res.statusText,
        body: errorBody,
      }),
    );
  }

  return res.json();
};'
  FROM system_profile p, inserted_version_http_request v
  RETURNING id
),
inserted_file_http_request_2 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'output-config.json', 'Json', '{
  "flags": {
    "allowInference": true
  },
  "schema": {
    "type": "object",
    "additionalProperties": true,
    "description": "Generic HTTP response payload (unknown shape)"
  }
}'
  FROM system_profile p, inserted_version_http_request v
  RETURNING id
),
inserted_file_http_request_3 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'package.json', 'Json', '{
  "name": "API Request"
}'
  FROM system_profile p, inserted_version_http_request v
  RETURNING id
),

-- Execute SQL
inserted_program_sql_query AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, 'Execute SQL', true FROM system_profile
  RETURNING id
),
inserted_version_sql_query AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '{"type":"object","properties":{"connection":{"type":"object","properties":{"dialect":{"type":"string","enum":["Postgres","MySQL"]},"return_mode":{"type":"string","enum":["Rows","Count"]}}},"query":{"type":"string","title":"SQL Query"}},"required":["connection","query"]}', '{"flags":{"allowInference":true},"schema":{"type":"array","items":{"type":"object"},"description":"Query result rows"},"overloads":[{"match":{"connection.return_mode":"Count"},"schema":{"type":"number","description":"The total number of matching rows"}}]}' FROM inserted_program_sql_query
  RETURNING id
),
inserted_file_sql_query_0 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'input-schema.json', 'Json', '{
  "type": "object",
  "properties": {
    "connection": {
      "type": "object",
      "properties": {
        "dialect": {
          "type": "string",
          "enum": ["Postgres", "MySQL"]
        },
        "return_mode": {
          "type": "string",
          "enum": ["Rows", "Count"]
        }
      }
    },
    "query": {
      "type": "string",
      "title": "SQL Query"
    }
  },
  "required": ["connection", "query"]
}'
  FROM system_profile p, inserted_version_sql_query v
  RETURNING id
),
inserted_file_sql_query_1 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'main.ts', 'TypeScript', 'export default async ({ input }) => {
  throw new Error(
    `SQL execution for ${input.connection.dialect} is not yet implemented`,
  );
};'
  FROM system_profile p, inserted_version_sql_query v
  RETURNING id
),
inserted_file_sql_query_2 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'output-config.json', 'Json', '{
  "flags": {
    "allowInference": true
  },
  "schema": {
    "type": "array",
    "items": { "type": "object" },
    "description": "Query result rows"
  },
  "overloads": [
    {
      "match": { "connection.return_mode": "Count" },
      "schema": {
        "type": "number",
        "description": "The total number of matching rows"
      }
    }
  ]
}'
  FROM system_profile p, inserted_version_sql_query v
  RETURNING id
),
inserted_file_sql_query_3 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'package.json', 'Json', '{
  "name": "Execute SQL"
}'
  FROM system_profile p, inserted_version_sql_query v
  RETURNING id
),

-- Uppercase String
inserted_program_uppercase_string AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, 'Uppercase String', true FROM system_profile
  RETURNING id
),
inserted_version_uppercase_string AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '{"type":"object","properties":{"text_to_format":{"type":"string","title":"Text","description":"The string you want to capitalize"}},"required":["text_to_format"]}', '{"flags":{},"schema":{"type":"string","description":"The capitalized string"}}' FROM inserted_program_uppercase_string
  RETURNING id
),
inserted_file_uppercase_string_0 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'input-schema.json', 'Json', '{
  "type": "object",
  "properties": {
    "text_to_format": {
      "type": "string",
      "title": "Text",
      "description": "The string you want to capitalize"
    }
  },
  "required": ["text_to_format"]
}'
  FROM system_profile p, inserted_version_uppercase_string v
  RETURNING id
),
inserted_file_uppercase_string_1 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'main.ts', 'TypeScript', 'export default ({ input }) => input.text_to_format.toUpperCase();'
  FROM system_profile p, inserted_version_uppercase_string v
  RETURNING id
),
inserted_file_uppercase_string_2 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'output-config.json', 'Json', '{
  "flags": {},
  "schema": {
    "type": "string",
    "description": "The capitalized string"
  }
}'
  FROM system_profile p, inserted_version_uppercase_string v
  RETURNING id
),
inserted_file_uppercase_string_3 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'package.json', 'Json', '{
  "name": "Uppercase String"
}'
  FROM system_profile p, inserted_version_uppercase_string v
  RETURNING id
),

-- User Input
inserted_program_user_input AS (
  INSERT INTO "program" (owner_profile_id, name, first_party)
  SELECT id, 'User Input', true FROM system_profile
  RETURNING id
),
inserted_version_user_input AS (
  INSERT INTO "program_version" (program_id, "version", input_schema, output_config)
  SELECT id, 1, '{"type":"object","properties":{"format":{"type":"string","enum":["string","number","boolean"],"title":"Column Type","default":"string"}},"required":["format"]}', '{"flags":{"allowManualInput":true},"schema":{"type":"string","description":"Standard text value"},"overloads":[{"match":{"format":"number"},"schema":{"type":"number"}},{"match":{"format":"boolean"},"schema":{"type":"boolean"}}]}' FROM inserted_program_user_input
  RETURNING id
),
inserted_file_user_input_0 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'input-schema.json', 'Json', '{
  "type": "object",
  "properties": {
    "format": {
      "type": "string",
      "enum": ["string", "number", "boolean"],
      "title": "Column Type",
      "default": "string"
    }
  },
  "required": ["format"]
}'
  FROM system_profile p, inserted_version_user_input v
  RETURNING id
),
inserted_file_user_input_1 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'main.ts', 'TypeScript', 'export default ({ input, cell }) => {
  const raw = cell.manualInputValue;

  switch (input.format) {
    case "number":
      return Number(raw);
    case "boolean":
      return raw?.toLowerCase() === "true";
    default:
      return raw;
  }
};'
  FROM system_profile p, inserted_version_user_input v
  RETURNING id
),
inserted_file_user_input_2 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'output-config.json', 'Json', '{
  "flags": {
    "allowManualInput": true
  },
  "schema": {
    "type": "string",
    "description": "Standard text value"
  },
  "overloads": [
    {
      "match": { "format": "number" },
      "schema": { "type": "number" }
    },
    {
      "match": { "format": "boolean" },
      "schema": { "type": "boolean" }
    }
  ]
}'
  FROM system_profile p, inserted_version_user_input v
  RETURNING id
),
inserted_file_user_input_3 AS (
  INSERT INTO "program_file" (owner_profile_id, version_id, filename, filetype, content)
  SELECT p.id, v.id, 'package.json', 'Json', '{
  "name": "User Input"
}'
  FROM system_profile p, inserted_version_user_input v
  RETURNING id
),

program_version_formula AS (
  SELECT id FROM inserted_version_formula LIMIT 1
),

program_version_http_request AS (
  SELECT id FROM inserted_version_http_request LIMIT 1
),

program_version_sql_query AS (
  SELECT id FROM inserted_version_sql_query LIMIT 1
),

program_version_uppercase_string AS (
  SELECT id FROM inserted_version_uppercase_string LIMIT 1
),

program_version_user_input AS (
  SELECT id FROM inserted_version_user_input LIMIT 1
),

-- Demo table

inserted_table AS (
  INSERT INTO "table" (owner_profile_id, name)
  SELECT id, 'Demo Table' FROM system_profile
  RETURNING id
),

-- Demo row

inserted_row AS (
  INSERT INTO "row" (table_id, "idx")
  SELECT id, 0 FROM inserted_table
  RETURNING id
),

-- Demo columns: col 0 = user input, col 1 = uppercase transform

inserted_col1 AS (
  INSERT INTO "column" (table_id, name, "idx", program_version_id, input_template, output_schema)
  SELECT
    t.id,
    'Input',
    0,
    p.id,
    '{"format": "string"}',
    '{"type":"string","description":"Standard text value"}'
  FROM inserted_table t, program_version_user_input p
  RETURNING id
),

inserted_col2 AS (
  INSERT INTO "column" (table_id, name, "idx", program_version_id, input_template, output_schema)
  SELECT
    t.id,
    'Uppercased',
    1,
    p.id,
    '{"text_to_format.$": "$.columns.' || c1.id || '.value"}',
    '{"type":"string","description":"The capitalized string"}'
  FROM inserted_table t, program_version_uppercase_string p, inserted_col1 c1
  RETURNING id
),

-- Dependency: col 1 (uppercase) depends on col 0 (user input)

_dep AS (
  INSERT INTO column_dependency (source_column_id, target_column_id)
  SELECT c1.id, c2.id
  FROM inserted_col1 c1, inserted_col2 c2
),

-- Demo cells

_cell1 AS (
  INSERT INTO cell (column_id, row_id, manual_input)
  SELECT c1.id, r.id, 'hello world'
  FROM inserted_col1 c1, inserted_row r
),

_cell2 AS (
  INSERT INTO cell (column_id, row_id)
  SELECT c2.id, r.id
  FROM inserted_col2 c2, inserted_row r
)

SELECT 1;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.table;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.row;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.column;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.cell;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DROP POLICY IF EXISTS "Users can view tables they own" ON public.table;
DROP POLICY IF EXISTS "Users can view rows in their own tables" ON public.row;
DROP POLICY IF EXISTS "Users can view columns in their own tables" ON public.column;
DROP POLICY IF EXISTS "allow_select_cells" ON public.cell;
DROP POLICY IF EXISTS "Users can view cells in their own tables" ON public.cell;
CREATE POLICY "Users can view tables they own" ON public."table"
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.profile
    WHERE profile.id = "table".owner_profile_id
      AND profile.owner_user_id = auth.uid()
  )
);

CREATE POLICY "Users can view rows in their own tables" ON public."row"
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public."table"
    JOIN public.profile ON profile.id = "table".owner_profile_id
    WHERE "table".id = "row".table_id
      AND profile.owner_user_id = auth.uid()
  )
);

CREATE POLICY "Users can view columns in their own tables" ON public."column"
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public."table"
    JOIN public.profile ON profile.id = "table".owner_profile_id
    WHERE "table".id = "column".table_id
      AND profile.owner_user_id = auth.uid()
  )
);

CREATE POLICY "Users can view cells in their own tables" ON public.cell
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public."row"
    JOIN public."table" ON "table".id = "row".table_id
    JOIN public.profile ON profile.id = "table".owner_profile_id
    WHERE "row".id = cell.row_id
      AND profile.owner_user_id = auth.uid()
  )
);
