import type { Command } from "commander";
import {
  createCellCommand,
  createCellsCommand,
  createColumnCommand,
  createColumnsCommand,
  createEventCommand,
  createEventsCommand,
  createKeyCommand,
  createKeysCommand,
  createPipeCommand,
  createPipesCommand,
  createProfileCommand,
  createProfilesCommand,
  createProgramCommand,
  createProgramFilesCommand,
  createProgramsCommand,
  createProgramVersionsCommand,
  createProjectCommand,
  createProjectsCommand,
  createRowCommand,
  createRowsCommand,
  createRunCommand,
  createSecretBindingsCommand,
  createSecretCommand,
  createSecretsCommand,
  createSidebarCommand,
  createSourceCommand,
  createSourceEventCommand,
  createSourceEventsCommand,
  createSourcesCommand,
  createTableCommand,
  createTablesCommand,
} from "./resources";

const commandFactories = [
  createProjectCommand,
  createProjectsCommand,
  createProfileCommand,
  createProfilesCommand,
  createKeyCommand,
  createKeysCommand,
  createSecretCommand,
  createSecretsCommand,
  createTableCommand,
  createTablesCommand,
  createColumnCommand,
  createColumnsCommand,
  createRowCommand,
  createRowsCommand,
  createCellCommand,
  createCellsCommand,
  createRunCommand,
  createProgramCommand,
  createProgramsCommand,
  createProgramVersionsCommand,
  createProgramFilesCommand,
  createSourceCommand,
  createSourcesCommand,
  createSourceEventCommand,
  createSourceEventsCommand,
  createPipeCommand,
  createPipesCommand,
  createSecretBindingsCommand,
  createEventCommand,
  createEventsCommand,
  createSidebarCommand,
] as const;

export function registerCommands(rootCommand: Command) {
  for (const createCommand of commandFactories) {
    rootCommand.addCommand(createCommand());
  }
}
