import type { ApiModel } from "../model";

/**
 * Emits a standalone CLI for the reverse-engineered API — a generic Commander
 * pass-through that introspects the generated contract and dispatches through
 * the generated SDK, exactly like the Marble/HARP CLIs. Every operation becomes
 * `<cli> <resource> <operation> '<json>'`.
 */
export const generateCli = (model: ApiModel): string =>
  [
    "#!/usr/bin/env node",
    "// Generated by HARP \uD83E\uDE89 — CLI for the reverse-engineered API.",
    `// Source: ${model.host}`,
    "",
    'import { isContractProcedure } from "@orpc/contract";',
    'import { Command } from "commander";',
    'import { targetContract } from "./contract";',
    'import { createClient } from "./sdk";',
    "",
    "type Dispatch = (input: unknown) => Promise<unknown>;",
    "const client = createClient({",
    '  baseUrl: process.env.API_URL ?? "http://localhost:3000",',
    "}) as unknown as Record<string, Record<string, Dispatch>>;",
    "",
    'const root = new Command().name("api").description("Generated API client.");',
    "",
    "for (const [resource, operations] of Object.entries(targetContract)) {",
    "  const group = new Command(resource);",
    "  for (const [operation, procedure] of Object.entries(",
    "    operations as Record<string, unknown>,",
    "  )) {",
    "    if (!isContractProcedure(procedure)) {",
    "      continue;",
    "    }",
    "    group",
    "      .command(operation)",
    '      .argument("[input]", "JSON input")',
    "      .action(async (input?: string) => {",
    "        const result = await client[resource][operation](",
    "          input ? JSON.parse(input) : {},",
    "        );",
    "        console.log(JSON.stringify(result, null, 2));",
    "      });",
    "  }",
    "  root.addCommand(group);",
    "}",
    "",
    "await root.parseAsync(process.argv);",
    "",
  ].join("\n");
