import {
  operationVerb,
  pickCollectionTemplate,
  pickItemTemplate,
} from "../infer/path";
import type {
  ApiModel,
  EndpointModel,
  ResourceModel,
  SchemaField,
  SchemaNode,
} from "../model";
import { schemaNodeToZod } from "./zod";

/**
 * Emits a standalone, fully-typed oRPC contract for a reverse-engineered API.
 * The output depends only on `@orpc/contract` + `zod`, so it can be lifted into
 * any project and wired to a Hono/oRPC server — the second "just as beautiful"
 * oRPC layer HARP produces.
 */

const isIdentifier = (key: string) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);

const safeVar = (name: string) => (isIdentifier(name) ? name : `r_${name}`);

const capitalize = (value: string) =>
  value.length === 0 ? value : `${value[0].toUpperCase()}${value.slice(1)}`;

const uniqueName = (base: string, used: Set<string>) => {
  const candidate = base.length === 0 ? "operation" : base;
  if (!used.has(candidate)) {
    used.add(candidate);
    return candidate;
  }
  let suffix = 2;
  while (used.has(`${candidate}${suffix}`)) {
    suffix += 1;
  }
  used.add(`${candidate}${suffix}`);
  return `${candidate}${suffix}`;
};

const inputNodeFor = (endpoint: EndpointModel): SchemaNode | null => {
  const fields: SchemaField[] = endpoint.pathParams.map((param) => ({
    key: param.name,
    optional: false,
    schema: param.schema,
  }));
  if (endpoint.query !== null) {
    fields.push({
      key: "query",
      optional: true,
      schema: endpoint.query,
    });
  }
  if (endpoint.requestBody !== null) {
    fields.push({
      key: "body",
      optional: false,
      schema: endpoint.requestBody,
    });
  }
  if (fields.length === 0) {
    return null;
  }
  return {
    fields,
    kind: "object",
    nullable: false,
  };
};

const renderOperation = (
  endpoint: EndpointModel,
  operationName: string,
  resourceName: string,
): string => {
  const tag = capitalize(resourceName);
  const summary = `${capitalize(operationName)} ${resourceName}`;
  const input = inputNodeFor(endpoint);
  const output = endpoint.responseBody ?? {
    kind: "unknown",
  };
  const inputLine =
    input === null ? "" : `\n    .input(${schemaNodeToZod(input, 2)})`;
  return [
    `  ${operationName}: oc`,
    "    .route({",
    `      method: "${endpoint.method}",`,
    `      operationId: "${resourceName}.${operationName}",`,
    `      path: "${endpoint.pathTemplate}",`,
    `      summary: "${summary}",`,
    `      tags: ["${tag}"],`,
    "    })",
  ]
    .join("\n")
    .concat(inputLine)
    .concat(`\n    .output(${schemaNodeToZod(output, 2)}),`);
};

const renderResource = (resource: ResourceModel): string => {
  const templates = resource.endpoints.map((endpoint) => endpoint.pathTemplate);
  const collection = pickCollectionTemplate(templates);
  const item = pickItemTemplate(templates, collection);
  const used = new Set<string>();
  const operations = resource.endpoints.map((endpoint) => {
    const verb = operationVerb(
      endpoint.method,
      endpoint.pathTemplate,
      collection,
      item,
    );
    const operationName = uniqueName(verb, used);
    return renderOperation(endpoint, operationName, resource.name);
  });
  return `const ${safeVar(resource.name)}Contract = {\n${operations.join("\n")}\n};`;
};

export const generateContract = (model: ApiModel): string => {
  const header = [
    "// Generated by HARP \uD83E\uDE89 — do not edit by hand.",
    `// Source: ${model.host}`,
    `// Generated: ${model.generatedAt}`,
    "",
    'import { oc } from "@orpc/contract";',
    'import { z } from "zod";',
    "",
  ].join("\n");

  const resources = model.resources.map(renderResource).join("\n\n");

  const rootEntries = model.resources
    .map((resource) => `  ${resource.name}: ${safeVar(resource.name)}Contract,`)
    .join("\n");
  const root = [
    "",
    "",
    "export const targetContract = {",
    rootEntries,
    "};",
    "",
    "export type TargetContract = typeof targetContract;",
    "",
  ].join("\n");

  return `${header}\n${resources}\n${root}`;
};
