import type { ApiModel } from "../model";

/**
 * Emits a standalone, fully-typed SDK for the reverse-engineered API — a thin
 * oRPC client over the generated contract, exactly like Marble's SDK. Consumers
 * get `api.<resource>.<operation>(input)` with full inference.
 */
export const generateSdk = (model: ApiModel): string =>
  [
    "// Generated by HARP \uD83E\uDE89 — typed SDK for the reverse-engineered API.",
    `// Source: ${model.host}`,
    "",
    'import { createORPCClient } from "@orpc/client";',
    'import { RPCLink } from "@orpc/client/fetch";',
    'import type { ContractRouterClient } from "@orpc/contract";',
    'import { targetContract } from "./contract";',
    "",
    "export type TargetClient = ContractRouterClient<typeof targetContract>;",
    "",
    "export type ClientOptions = {",
    "  baseUrl: string;",
    "  fetch?: typeof fetch;",
    "  headers?: Record<string, string>;",
    "};",
    "",
    "export const createClient = (options: ClientOptions): TargetClient => {",
    "  const link = new RPCLink({",
    "    fetch: options.fetch,",
    "    headers: () => options.headers ?? {},",
    '    url: () => options.baseUrl.replace(/\\/+$/, "") + "/rpc",',
    "  });",
    "  return createORPCClient(link) as TargetClient;",
    "};",
    "",
  ].join("\n");
